### ISSUE TITLE
Error while running the code

### ISSUE THREAD

**Issue by Radhika-aquarius** [DavidUser/GraphQL-Cpp#1]
When I try to run the main.cpp I get the following error-
g++ main.cpp 
In file included from main.cpp:3:0:
graphql.h:11:8: error: ‘void GraphQL::Query(std::__cxx11::string, Resolver ...) [with T = Custumer; Resolver = {main()::<lambda(std::__cxx11::string)>}; std::__cxx11::string = std::__cxx11::basic_string<char>]’, declared using local type ‘main()::<lambda(std::__cxx11::string)>’, is used but never defined [-fpermissive]
   void Query(string name, Resolver... resolver);

**Comment by ender233** [comment]
the same problem. why there was no implementation of that?

**Comment by davidkennedydev** [comment]
It's just an initial concept,. At last week I try the first implementations, but the desired implementation depends on non intrusive reflection (maybe on language standard C++20). 
Thank's by the interest, now that it's seems something useful, I'll dedicate more time to implement. 
However any help are welcome.
